version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  fast-meet:
    env_file:
      - client/.env
      - server/.env
    command: npm run deploy --unsafe-perm=true --allow-root
    